### ISSUE TITLE
Create a gitignored config/env/local.js

### ISSUE THREAD

**Issue by ravenjohn** [anyTV/anytv-node-boilerplate#96]
The idea is this local config will override whatever is the current environment config but it won't be pushed. Best for "server only" config values or for machine-specific config.

**Comment by pandafox** [comment]
Well the default would be env/development.js I think?

**Comment by ravenjohn** [comment]
The hierarchy would be:

`config/env/local.js` overrides `config/env/${ node_env }.js` overrides `config/config.js`

where the default node_env is `development`

**Comment by pandafox** [comment]
Hum okay, that's an interesting idea, perhaps it'll work but I thought the ideal would be

default - all dev configs and defaults to be shared across all env
env/dev - user to overwrite with running locally
env/staging - staging config
env/production - live config

I guess perhaps we should just ignore all env setting since all setting should be just in default with fallback to environment dev?

Not sure what would benefit of local add to that we don't have already with env/dev?

**Comment by ravenjohn** [comment]
Issue solved in https://github.com/anyTV/anytv-node-boilerplate/pull/108
